### ISSUE TITLE
[Question] Where's the tools menu?

### ISSUE THREAD

**Issue by qwinkler** [difurious/lightweight-charts-line-tools#7]
First of all - thanks for the repo, it's big and great work!

However, I have a question: how to open the tools menu, so I can draw on a chart via UI, not via code?

I cloned the repo, installed dependencies via `npm i --force`, and built it via `npm run build:prod`.
I opened the `debug.html` and it works:
<img width="1792" alt="Screenshot 2024-05-10 at 21 08 47" src="https://github.com/difurious/lightweight-charts-line-tools/assets/18363937/bd70b77c-2c49-4fa3-9187-07862950b84c">

But I don't see the "menu" of the tools (from the video in readme):
<img width="822" alt="Screenshot 2024-05-10 at 21 09 25" src="https://github.com/difurious/lightweight-charts-line-tools/assets/18363937/e10d06d6-9352-4ac4-995b-500f3779be3c">

I'm not into front development so I may be missing something.

Thanks in advance for the answer.

**Comment by difurious** [comment]
@qwinkler Those tools are custom front end buttons.  They do not exist in the build.  So you would make a button, and on click that button calls the `chart.current.addLineTool("HorizontalLine",[],{})` So yes you need to do front end code. lightweight-charts in general requires you to code to even get it to work.  The debug.html show you code examples on how to do things.
